services:
  backend:
    image: slvk_backend
    build: 
      context: ./Slovko.NL.Api
    ports:
      - "7075:7075"
    restart: always
    environment:
     - ASPNETCORE_URLS=http://+:7075
  frontend:
    image: slvk_frontend
    build: 
      context: ./frontend
      args:
        - BACKEND_HOST=${BACKEND_HOST}
        - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:80"
    restart: always
    env_file:
      - .env
    depends_on:
      - backend
