services:
  backend:
    image: slvk_backend
    build: 
      context: ./Slovko.NL.Api
    ports:
      - "7075:7075"
    environment:
     - ASPNETCORE_URLS=http://+:7075
  frontend:
    image: slvk_frontend
    build: 
      context: ./frontend
    ports:
      - "80:80"
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 7075
    depends_on:
      - backend