name: Deploy on arch 

on:
  push:
    branches:
      - develop


jobs:
  build-and-publish:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          submodules: 'true'
        continue-on-error: false
        
      - name: set backend ip
        run: echo BACKEND_HOST=${{ vars.BACKEND_HOST }} > .env

      - name: set backend ip
        run: echo BACKEND_PORT=${{ vars.BACKEND_PORT }} >> .env
        continue-on-error: false
        
      - name: check results
        run: cat  .env
        continue-on-error: false
        
      - name: Start application-specific services using Docker Compose
        run: docker compose up -d --build
        continue-on-error: false
